/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
export const up = async (knex) => {
    // Remove the old check constraint and add the new one
    // The constraint name may be autogenerated, so we use raw SQL to drop and add
    await knex.schema.raw(`
        ALTER TABLE progress DROP CONSTRAINT IF EXISTS progress_level_status_check;
        ALTER TABLE progress ADD CONSTRAINT progress_level_status_check CHECK (level_status IN ('incomplete', 'complete', 'reviewed'));
    `)
}

/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
export const down = async (knex) => {
    await knex.schema.raw(`
        ALTER TABLE progress DROP CONSTRAINT IF EXISTS progress_level_status_check;
        ALTER TABLE progress ADD CONSTRAINT progress_level_status_check CHECK (level_status IN ('incomplete', 'complete'));
    `)
}
